---
language: python
python: "2.7"

before_install:
    - pip install -r requirements.txt
    - pip install python-coveralls

install:
    - pip install -e .

script: 
    - nosetests -v --with-coverage
    - ls -Falh

after_success: 
    - coveralls
